import { SongMetadata } from '../utils/types';

const songMetadata: SongMetadata[] = [
    { number: 1, title: 'Panie, zmiłuj się' },
    { number: 2, title: 'Gloria' },
    { number: 3, title: 'Chwała na wysokości' },
    { number: 4, title: 'Alleluja' },
    { number: 5, title: 'O usłysz mój głos - modlitwa wiernych' },
    { number: 6, title: 'Święty, święty' },
    { number: 7, title: 'Ojcze nasz' },
    { number: 8, title: 'Baranku Boży' },
    { number: 9, title: 'Tryumfy Króla Niebieskiego' },
    { number: 10, title: 'Gdy śliczna Panna' },
    { number: 11, title: 'Lulajże, Jezuniu' },
    { number: 12, title: 'Z Narodzenia Pana' },
    { number: 13, title: 'Przybieżeli do Betlejem' },
    { number: 14, title: 'Dzisiaj w Betlejem' },
    { number: 15, title: 'Nie płaczże, mój Syneczku' },
    { number: 16, title: 'Cicha noc' },
    { number: 17, title: 'Jezusa narodzonego' },
    { number: 18, title: 'Pastuszkowie bracia mili' },
    { number: 19, title: 'Gdy się Chrystus rodzi' },
    { number: 20, title: 'Pójdźmy wszyscy do stajenki' },
    { number: 21, title: 'Ciemne niebo świat otula' },
    { number: 22, title: 'Prawda jedyna' },
    { number: 23, title: 'Drzewo krzyża surowe' },
    { number: 24, title: 'Dzięki za Twój krzyż' },
    { number: 25, title: 'Golgoto, Golgoto, Golgoto' },
    { number: 26, title: 'Zbawienie przyszło przez krzyż' },
    { number: 27, title: 'Żydowski Król, Boży Syn' },
    { number: 28, title: 'Bez wstążek lub balonów' },
    { number: 29, title: 'Rozpięty na ramionach' },
    { number: 30, title: 'Psalm "Hosanna"' },
    { number: 31, title: 'Uwielbiam Imię Twoje, Panie' },
    { number: 32, title: 'Zaśpiewajcie Panu pieśń nową' },
    { number: 33, title: 'Po szabacie pierwszego dnia z rana' },
    { number: 34, title: 'Wody nie ugaszą jej' },
    { number: 35, title: 'Zmartwychwstał Pan i żyje dziś' },
    { number: 36, title: 'Oto są baranki młode' },
    { number: 37, title: 'Ty tylko mnie poprowadź' },
    { number: 38, title: 'Swojego Ducha, Panie' },
    { number: 39, title: 'Alleluja (Cohen)' },
    { number: 40, title: 'Maryjo, Matko mojego wezwania' },
    { number: 41, title: 'Twoja Miłość' },
    { number: 42, title: 'Powietrzem moim jest' },
    { number: 43, title: 'Kochany bracie, kochana siostro' },
    { number: 44, title: 'Pan jest Pasterzem moim (laj, la laj)' },
    { number: 45, title: 'Do Ciebie, Panie, woła dusza moja' },
    { number: 46, title: 'Maryjo, oddana Panu' },
    { number: 47, title: 'Nic nie musisz mówić nic' },
    { number: 48, title: 'Wszystko, co dziś mamy' },
    { number: 49, title: 'Cisza' },
    { number: 50, title: 'Mój Pan mocą moją jest' },
    { number: 51, title: 'Będziemy tańczyć, będziemy śpiewać' },
    { number: 52, title: 'Niech Wam błogosławi Pan' },
    { number: 53, title: 'Śpiewajcie Panu, sławcie Go' },
    { number: 54, title: 'Jezus dziś przyszedł do mnie' },
    { number: 55, title: 'Wykrzykujcie na cześć Pana' },
    { number: 56, title: 'Nie bójcie się żyć dla miłości' },
    { number: 57, title: 'Otwierasz niebo' },
    { number: 58, title: 'Mój ląd' },
    { number: 59, title: 'Schowaj mnie' },
    { number: 60, title: 'Niechaj zstąpi Duch Twój' },
    { number: 61, title: 'Błogosławieni miłosierni' },
    { number: 62, title: 'Stoję dziś' },
    { number: 63, title: 'Mów do mnie Panie' },
    { number: 64, title: 'Dotknij, Panie, moich oczu' },
    { number: 65, title: 'Uwielbiajcie Pana' },
    { number: 66, title: 'Oto ja, poślij mnie' },
    { number: 67, title: 'W ciele Chrystusa tworzymy jedno' },
    { number: 68, title: 'Ukojenie' },
    { number: 69, title: 'Więcej miłości, więcej mocy' },
    { number: 70, title: 'Duchu Święty, Stworzycielu' },
    { number: 71, title: 'Jezus, najwyższe Imię' },
    { number: 72, title: 'Duchu Święty, obiecany nam' },
    { number: 73, title: 'Ja dziękuję Ci' },
    { number: 74, title: 'Duchu Święty, pouczaj mnie' },
    { number: 75, title: 'Nasz Pan jest potężny' },
    { number: 76, title: 'Jesteśmy piękni Twoim pięknem' },
    { number: 77, title: 'Godzien, o godzien' },
    { number: 78, title: 'Nasz Bóg jest wielki' },
    { number: 79, title: 'Będę śpiewał Tobie' },
    { number: 80, title: 'Wszyscy ludzie klaszczą w dłonie' },
    { number: 81, title: 'Duchu Święty, przyjdź i rozpal nas' },
    { number: 82, title: 'Miałem Pana zawsze przed oczami' },
    { number: 83, title: 'Oddajmy cześć wiecznemu Panu chwał' },
    { number: 84, title: 'Panu naszemu pieśni grajcie' },
    { number: 85, title: 'Moje wędrowanie' },
    { number: 86, title: 'Przyjaciela mam' },
    { number: 87, title: 'Jezus, pokonał śmierć' },
    { number: 88, title: 'Jedyny Pan, prawdziwy Bóg' },
    { number: 89, title: 'Jezus uzdrawia dziś' },
    { number: 90, title: 'Jak dobrze jest dziękować Ci, Panie' },
    { number: 91, title: 'W Tobie jest światło' },
    { number: 92, title: 'O, Panie, Ty nam dajesz' },
    { number: 93, title: 'Boże, Ojcze na niebie' },
    { number: 94, title: 'Przed Tobą, Wszechmocny' },
    { number: 95, title: 'Szukam Cię, Panie, o wschodzie' },
    { number: 96, title: 'Śpiewaj Panu, swemu Bogu serce daj' },
    { number: 97, title: 'Ukaż mi, Panie, Swą twarz' },
    { number: 98, title: 'Panie, Twój tron' },
    { number: 99, title: 'Nic nie odłączy mnie' },
    { number: 100, title: 'Każdy wschód słońca' },
    { number: 101, title: 'Nie lękajcie się' },
    { number: 102, title: 'Ofiaruję Tobie, Panie mój' },
    { number: 103, title: 'Jestem tu, by wielbić' },
    { number: 104, title: 'Daję Ci serce moje Panie' },
    { number: 105, title: 'Jezus daje nam zbawienie' },
    { number: 106, title: 'Boże Twa łaska nad nami jest' },
    { number: 107, title: 'Szedłem kiedyś Jezu' },
    { number: 108, title: 'Pokorna służebnico Pana' },
    { number: 109, title: 'Jestem do Niego podobny' },
    { number: 110, title: 'Będę z aniołami śpiewał, alleluja' },
    { number: 111, title: 'Zbudowani na Chrystusie' },
    { number: 112, title: 'Duchu miłości, wylewaj się na nas' },
    { number: 113, title: 'Albowiem tak Bóg umiłował świat' },
    { number: 114, title: 'W kruszynie chleba' },
    { number: 115, title: 'Spocznij na nas, Duchu Pana' },
    { number: 116, title: 'Uwielbiam Cię, błogosławię Cię' },
    { number: 117, title: 'Pan jest mocą swojego ludu' },
    { number: 118, title: 'Ty masz moc uzdrowienia' },
    { number: 119, title: 'Łaską jesteśmy zbawieni' },
    { number: 120, title: 'Kiedyś wino i chleb' },
    { number: 121, title: 'Duchu Święty ogarnij mnie' },
    { number: 122, title: 'Fundamentem jest miłość' },
    { number: 123, title: 'Czekam na Ciebie, dobry Boże' },
    { number: 124, title: 'Raduje się dusza ma' },
    { number: 125, title: 'Modlitwa o Miłość (Zabierz Panie i przyjmij)' },
    { number: 126, title: 'W Twoje ręce, o Matko' },
    { number: 127, title: 'Chcę wywyższać Imię Twe' },
    { number: 128, title: 'Nadzieja nosi niebieską sukienkę' },
    { number: 129, title: 'Ubi caritas' },
    { number: 130, title: 'Kocham, więc nie muszę się bać' },
    { number: 131, title: 'W lekkim powiewie' },
    { number: 132, title: 'Hosanna, hosanna' },
    { number: 133, title: 'To jest Baranka Ciało, Jego Krew' },
    { number: 134, title: 'Emmanuel, Emmanuel' },
    { number: 135, title: 'Oto idzie mój Bóg' },
    { number: 136, title: 'Pomódl się, Miriam' },
    { number: 137, title: 'Maryjo, wzorze prostoty' },
    { number: 138, title: 'Jestem dzieckiem Boga' },
    { number: 139, title: 'Jezus jest z nami tu' },
    { number: 140, title: 'Niech zabrzmi Panu chwała w niebiosach' },
    { number: 141, title: 'Barka' },
    { number: 142, title: 'Ja Jestem' },
    { number: 143, title: 'Jezu, Źródło' },
    { number: 144, title: 'Nie bój się, wypłyń na głębię' },
    { number: 145, title: 'Niepojęty, niezmierzony' },
    { number: 146, title: 'Witaj, Pokarmie' },
    { number: 147, title: 'Chrystus Pan karmi nas' },
    { number: 148, title: 'O, Jezu, w Hostii utajony' },
    { number: 149, title: 'Ta krew z grzechu obmywa nas' },
    { number: 150, title: 'Przyodziałeś mnie, Panie' },
    { number: 151, title: 'Jezus, Królem naszym jest' },
    { number: 152, title: 'Wypłyń na głębię' },
    { number: 153, title: 'Idzie mój Pan' },
    { number: 154, title: 'Z Jezusem w chwale Ojca' },
    { number: 155, title: 'Odnajduję Cię' },
    { number: 156, title: 'Już teraz we mnie kwitną Twe ogrody' },
    { number: 157, title: 'Z Tobą ciemność nie będzie ciemna' },
    { number: 158, title: 'Mrok ogarnął całą ziemię' },
    { number: 159, title: 'Rzekł Pan stało się' },
    { number: 160, title: 'Zwykły chleb przemieniasz' },
    { number: 161, title: 'Abba Ojcze' },
    { number: 162, title: 'Błogosław duszo moja Pana' },
    { number: 163, title: 'W Swym Sercu na wieki ukryłeś nas' },
    { number: 164, title: 'Podnieś mnie, Jezu' },
    { number: 165, title: 'Ja wierzę, że to Jezus' },
    { number: 166, title: 'Jesteś Królem' },
    { number: 167, title: 'Przyjdź, królestwo Twoje' },
    { number: 168, title: 'Jesteś perłą' },
    { number: 169, title: 'Lud Twój, Panie, lud pielgrzymi' },
    { number: 170, title: 'Otwórz me oczy, chcę widzieć Jezusa' },
    { number: 171, title: 'Duchu Święty, błagam nie zwlekaj!' },
    { number: 172, title: 'Nie, nie, nie lękaj się' },
    { number: 173, title: 'Za to, że mnie ukochałeś' },
    { number: 174, title: 'Jezu,Tyś wszystkim dla mnie jest' },
    { number: 175, title: 'Pan mnie strzeże' },
    { number: 176, title: 'W Tobie cała nadzieja ma' },
    { number: 177, title: 'To mój Pan wiele mi uczynił' },
    { number: 178, title: 'Niech będzie chwała i cześć' },
    { number: 179, title: 'Kocham Twoją wolę, Panie' },
    { number: 180, title: 'Godzien chwały jest Baranek' },
    { number: 181, title: 'Oddaję Ci życie swe' },
    { number: 182, title: 'Jestem cały Twój' },
    { number: 183, title: 'Z okrzykiem radości wracamy na Syjon' },
    { number: 184, title: 'Mizerna, cicha' },
    { number: 185, title: 'Przyjdź jak deszcz (A. Gorączkowska)' },
    { number: 186, title: 'Niegodny' },
    { number: 187, title: 'Chwała Bogu Ojcu' },
    { number: 188, title: 'Chwała Panu i cześć' },
    { number: 189, title: 'Chwalcie Pana niebios' },
    { number: 190, title: 'Wszystkie narody klaskajcie w dłonie' },
    { number: 191, title: 'Hymn do Ducha Świętego' },
    { number: 192, title: 'O, Zbawcza Hostio' },
    { number: 193, title: 'Nie mądrość świata tego' },
    { number: 194, title: 'Blisko, blisko, blisko jesteś, Panie' },
    { number: 195, title: 'Boże wieczny, Boże żywy' },
    { number: 196, title: 'Ciebie pragnie dusza moja' },
    { number: 197, title: 'Pastorałka od serca do ucha' },
    { number: 198, title: 'Powstań i świeć' },
    { number: 199, title: 'Przybądź, Święty' },
    { number: 200, title: 'Jego Miłość' },
    { number: 201, title: 'Jestem tego pewien' },
    { number: 202, title: 'Powstań przyjaciółko ma' },
    { number: 203, title: 'Mroźna cisza' },
    { number: 204, title: 'Hymn ŚDM Panama 2019' },
    { number: 205, title: 'Memu Bogu, królowi' },
    { number: 206, title: 'Miłość uzdalnia mnie' },
    { number: 207, title: 'Panie Jezu, przyjdź' },
    { number: 208, title: 'Jahwe' },
    { number: 209, title: 'Nie chcę w innym miejscu być' },
    { number: 210, title: 'Duchu Święty, Tchnienie Ojca' },
    { number: 211, title: 'Yeshua (Jedno jest Imię pod niebem)' },
    { number: 212, title: 'Chcę tonąć w morzu Twego miłosierdzia' },
    { number: 213, title: 'Jak w Betlejem' },
    { number: 214, title: 'Otwórz me oczy, o Panie' },
    { number: 215, title: 'Krzyżu Święty, co świat obejmujesz' },
    { number: 216, title: 'Daj mi usłyszeć Twój głos' },
    { number: 217, title: 'Nie bój się, Ja Jestem' },
    { number: 218, title: 'Przybądź, Duchu Święty' },
    { number: 219, title: 'Wspaniały dawco miłości' },
    { number: 220, title: 'Zbliżam się w pokorze' },
    { number: 221, title: 'Duszo moja, Pana chwal' },
    { number: 222, title: 'Niech przyjęcie Ciała i Krwi' },
    { number: 223, title: 'Oceany' },
    { number: 224, title: 'Być bliżej Ciebie chcę' },
    { number: 225, title: 'Śpiewaj Jemu' },
    { number: 226, title: 'W żłobie leży' },
    { number: 227, title: 'Jakie piękne jest Imię Twe' },
    { number: 228, title: 'Mój Jezu, mój Zbawco' },
    { number: 229, title: 'Wykrzykujcie Bogu, wykrzykujcie Królowi' },
    { number: 230, title: 'Duszo ma, Pana chwal' },
    { number: 231, title: 'Zaufałem Panu i już' },
    { number: 232, title: 'Przyjdź, o Jezu, Maranatha!' },
    { number: 233, title: 'Przywołaj mnie, Panie, na pustynię' },
    { number: 234, title: 'Miłość przychodzi teraz (Jezus cię kocha)' },
    { number: 235, title: 'Taki jesteś Ty' },
    { number: 236, title: 'Pełen czci przed Tobą klękam' },
    { number: 237, title: 'Dom na skale' },
    { number: 238, title: 'Maryjo, chcę zamieszkać z Tobą' },
    { number: 239, title: 'Dzięki Ci, Maryjo' },
    { number: 240, title: 'Duchu Święty, Boże przyjdź' },
    { number: 241, title: 'Dziś jest czas, by oddać Bogu chwałę' },
    { number: 242, title: 'Chlebie najcichszy' },
    { number: 243, title: 'Przyjacielu, chcę zostać z Tobą' },
    { number: 244, title: 'O Matko, z Częstochowskiego wizerunku' },
    { number: 245, title: 'Koronka do Miłosierdzia Bożego' },
    { number: 246, title: 'Otwórzcie bramy' },
    { number: 247, title: 'Przybieżeli do Betlejem (żydowskie)' },
    { number: 248, title: 'Wśród nocnej ciszy' },
    { number: 249, title: 'Jezus malusieńki' },
    { number: 250, title: 'Gore gwiazda Jezusowi' },
    { number: 251, title: 'Jezu jesteś tu (Chwała)' },
    { number: 252, title: 'Modlitwa o pokój' },
    { number: 253, title: 'Sekwencja - Przybądź Duchu Święty' },
    { number: 254, title: 'Zjednoczeni w Duchu' },
    { number: 255, title: 'Życie trzeba umieć oddać' },
    { number: 256, title: 'Uwierz Polsko' },
    { number: 257, title: 'Niech Ci błogosławi Pan' },
    { number: 258, title: 'W żłobie leży (wersja 2)' },
    { number: 259, title: 'Żywy jest Kościół Twój' },
    { number: 260, title: 'Panie mój, przychodzę dziś' },
    { number: 261, title: 'Głoś imię Pana' },
    { number: 262, title: 'Niepokalana (J. Tomalak)' },
    { number: 263, title: 'Skrzypi wóz' },
    { number: 264, title: 'Bóg się rodzi' },
    { number: 265, title: 'Mędrcy świata, monarchowie' },
    { number: 266, title: 'Anioł pasterzom mówił' },
    { number: 267, title: 'Do szopy hej pasterze' },
    { number: 268, title: 'Cóż to za Dziecię' },
    { number: 269, title: 'Narodził się Jezus Chrystus' },
    { number: 270, title: 'Adeste, fideles' }
];

export default songMetadata;
